import fs from 'fs'
import path from 'path'
import productImagesManifest from '@/data/product-images.json'

// Build-time manifest: product slug -> [image URL paths]. Generated by
// scripts/build-product-images.mjs (run via the `prebuild` npm hook). We read
// images from this bundled JSON instead of fs.readdirSync(public/...) because
// `public/**` is excluded from the deployed serverless function bundle (see
// next.config.ts -> outputFileTracingExcludes). The image bytes are still
// served by the CDN at these same URL paths.
const PRODUCT_IMAGES = productImagesManifest as Record<string, string[]>
const MAX_IMAGES_PER_PRODUCT = 3

// Apply hero/card priority, then cap — mirrors the original readdir behavior.
function selectProductImages(all: string[] | undefined): string[] {
  const list = Array.isArray(all) ? all : []
  const priority = list.filter((p) => {
    const base = p.split('/').pop() || ''
    return base.includes('hero') || base.includes('card')
  })
  const chosen = priority.length > 0 ? priority : list
  return chosen.slice(0, MAX_IMAGES_PER_PRODUCT)
}

interface ProductEntry {
  slug: string
  name: { es: string; en: string }
  image_folder: string
}

interface ProductsCatalog {
  products: ProductEntry[]
}

let catalogCache: ProductEntry[] = []
let cacheLoaded = false

export async function loadProductsCatalog(): Promise<ProductEntry[]> {
  if (cacheLoaded && Array.isArray(catalogCache)) {
    return catalogCache
  }

  try {
    const catalogPath = path.join(process.cwd(), 'data/products.json')
    if (!fs.existsSync(catalogPath)) {
      console.warn('Products catalog not found at', catalogPath)
      catalogCache = []
      cacheLoaded = true
      return []
    }

    const data = fs.readFileSync(catalogPath, 'utf-8')
    const parsed = JSON.parse(data) as ProductsCatalog

    if (!Array.isArray(parsed.products)) {
      console.error('Products catalog invalid: products is not an array', typeof parsed.products)
      catalogCache = []
      cacheLoaded = true
      return []
    }

    catalogCache = parsed.products
    cacheLoaded = true
    return catalogCache
  } catch (error) {
    console.error('Failed to load products catalog:', error)
    catalogCache = []
    cacheLoaded = true
    return []
  }
}

export async function matchProductsInTopic(topic: string): Promise<string[]> {
  const catalog = await loadProductsCatalog()

  if (!Array.isArray(catalog)) {
    console.error('Catalog is not iterable:', typeof catalog)
    return []
  }

  const norm = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()
  const topicNorm = norm(topic)
  const topicWords = topicNorm.split(/[\s-]+/).filter(w => w.length > 3)
  const matchedImages: string[] = []
  const seen = new Set<string>()

  for (const product of catalog) {
    const nameEn = norm(product.name.en || '')
    const nameEs = norm(product.name.es || '')
    const slugNorm = norm(product.slug)
    const slugWords = product.slug.split('-').filter(w => w.length > 3).map(norm)

    const isMatch =
      topicNorm.includes(nameEn) ||
      topicNorm.includes(nameEs) ||
      nameEn.includes(topicNorm) ||
      nameEs.includes(topicNorm) ||
      topicNorm.includes(slugNorm) ||
      slugWords.some(w => topicNorm.includes(w)) ||
      topicWords.some(w => slugNorm.includes(w))

    if (isMatch) {
      for (const imagePath of selectProductImages(PRODUCT_IMAGES[product.slug])) {
        if (!seen.has(imagePath)) {
          matchedImages.push(imagePath)
          seen.add(imagePath)
        }
      }
    }
  }

  return matchedImages
}

export async function getProductImages(slug: string): Promise<string[]> {
  const catalog = await loadProductsCatalog()
  const product = catalog.find((p) => p.slug.toLowerCase() === slug.toLowerCase())

  if (!product) return []

  return selectProductImages(PRODUCT_IMAGES[product.slug])
}
